### ISSUE TITLE
Error con algunas series

### ISSUE THREAD

**Issue by Jadeka** [jsevilleja/service.subtitles.tusubtitulocom#1]
Me alegra encontrar un plugin que trabaje con la pagina tusubtitulo.com lo probé y corre muy bien, con excepción de algunas series que por algún motivo muestran error, te las menciono a continuación:
* DC legends of tomorrow
* Lucifer
* Flash
Espero que puedas revisar a que se debe el error y se pueda solucionar.

Gracias por este excelente plugin y sobre todo por tu tiempo y dedicacion

**Comment by jsevilleja** [comment]
Hola,

no sigo estas series... ¿puedes copiarme el nombre de fichero de un capítulo de cada una de ellas? Así tengo con que hacer pruebas. 

Saludos,

**Comment by Jadeka** [comment]
bueno revice un poco y en lo que entiendo creo que el problema ocurre porque en el caso de estas series el nombre lo jala pero en la pagina de tusubtitulo el nombre sale diferente 
Por ejemplo:

Para flash el consulta en la pagina como: "The Flash" pero la pagina lo tiene indexado como "The Flash 2014

Legends of tomorrow ====> DC's Legends Of Tomorrow
Lucifer ====> Lucifer (2015)

Aqui el kodi.log al final esta el error que sale al consultar lucifer
[kodi.txt](https://github.com/jsevilleja/service.subtitles.tusubtitulocom/files/276035/kodi.txt)

Los sub como salen en la pagina

[The Flash 2014 2x20 - Rupture (Español (Latinoamérica)).srt.txt](https://github.com/jsevilleja/service.subtitles.tusubtitulocom/files/276032/The.Flash.2014.2x20.-.Rupture.Espanol.Latinoamerica.srt.txt)
[DC's Legends Of Tomorrow 1x16 - Legendary (Español (Latinoamérica)).srt.txt](https://github.com/jsevilleja/service.subtitles.tusubtitulocom/files/276033/DC.s.Legends.Of.Tomorrow.1x16.-.Legendary.Espanol.Latinoamerica.srt.txt)
[Lucifer (2015) 1x13 - Take Me Back To Hell (Español (España)).srt.txt](https://github.com/jsevilleja/service.subtitles.tusubtitulocom/files/276034/Lucifer.2015.1x13.-.Take.Me.Back.To.Hell.Espanol.Espana.srt.txt)

Gracias por tu tiempo y espero que puedas corregir este error, sino no hay problema ya tu plugin es lo suficientemente bueno.

**Comment by jsevilleja** [comment]
Siento no poder ayudarte, pero no puedo hacer nada si en tusubtitulo.com le asignan un nombre diferente.
